# Generated by Django 5.1.7 on 2025-03-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('idade', models.PositiveIntegerField()),
                ('curso', models.CharField(max_length=50)),
                ('instituicao', models.CharField(max_length=100)),
                ('rm', models.PositiveIntegerField()),
            ],
        ),
    ]
