# Generated by Django 5.1.7 on 2025-03-28 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_usuario_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='qtd_animais',
            new_name='animais',
        ),
    ]
